### ISSUE TITLE
Missing go sdk moduules

### ISSUE THREAD

**Issue by johnsonhays** [aws-samples/amazon-ecr-continuous-scan#1]
Hi,

Am trying to build the code.  I run a make deploy but the code cannot load two modules, s3manager and external.

I do not see these directories in github.  How can I proceed?

[johnson@haysimp amazon-ecr-continuous-scan]$ make deploy
GOOS=linux GOARCH=amd64 go build -v -ldflags '-d -s -w' -a -tags netgo -installsuffix netgo -o bin/configs ./configs
configs/main.go:14:2: no required module provides package github.com/aws/aws-sdk-go-v2/aws/external; to add it:
	go get github.com/aws/aws-sdk-go-v2/aws/external
configs/main.go:16:2: no required module provides package github.com/aws/aws-sdk-go-v2/service/s3/s3manager; to add it:
	go get github.com/aws/aws-sdk-go-v2/service/s3/s3manager
make: *** [bconfigs] Error 1
[johnson@haysimp amazon-ecr-continuous-scan]$ go get github.com/aws/aws-sdk-go-v2/aws/external
go get: module github.com/aws/aws-sdk-go-v2@upgrade found (v1.3.0), but does not contain package github.com/aws/aws-sdk-go-v2/aws/external
[johnson@haysimp amazon-ecr-continuous-scan]$ go get github.com/aws/aws-sdk-go-v2/service/s3/s3manager
go get: module github.com/aws/aws-sdk-go-v2/service/s3@upgrade found (v1.3.0), but does not contain package github.com/aws/aws-sdk-go-v2/service/s3/s3manager
[johnson@haysimp amazon-ecr-continuous-scan]$ 

Thank you for your help.

Johnson Hays

**Comment by NDS-98** [comment]
Hi,

I also faced similar issue and have updated the repository with the latest Go module version. If you are still looking for a solution, you may refer my forked repo: https://github.com/NDS-98/amazon-ecr-continuous-scan/tree/fixed.

Naman

**Comment by mhausenblas** [comment]
Thanks a lot for the fixes @NDS-98  and incorporated now in https://github.com/aws-samples/amazon-ecr-continuous-scan/commit/31c5088d394c077446b2c95dd49dd370ee0acd64 (and moved to Go mods).
